-- return {
--     {
--         "sainnhe/sonokai",
--         priority = 1000,
--         config = function()
--             vim.g.sonokai_transparent_background = ".5"
--             vim.g.sonokai_enable_italic = "0"
--             vim.g.sonokai_style = "andromeda"
--             vim.cmd.colorscheme("sonokai")
--         end,
--     },
-- }
